development:
  clients:
    default:
      uri: mongodb+srv://Riyas:riyasgmail123@cluster0.6shao.mongodb.net/report?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5
production:
  clients:
    default:
      uri: mongodb+srv://Riyas:riyasgmail123@cluster0.6shao.mongodb.net/report?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5
test:
  clients:
    default:
      uri: mongodb+srv://Riyas:riyasgmail123@cluster0.6shao.mongodb.net/report?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5